// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: JournalProtocol.proto

package org.eligosource.eventsourced.core;

public final class JournalProtocol {
  private JournalProtocol() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public enum CommandType
      implements com.google.protobuf.ProtocolMessageEnum {
    WRITE_IN(0, 1),
    WRITE_OUT(1, 2),
    WRITE_ACK(2, 3),
    ;
    
    public static final int WRITE_IN_VALUE = 1;
    public static final int WRITE_OUT_VALUE = 2;
    public static final int WRITE_ACK_VALUE = 3;
    
    
    public final int getNumber() { return value; }
    
    public static CommandType valueOf(int value) {
      switch (value) {
        case 1: return WRITE_IN;
        case 2: return WRITE_OUT;
        case 3: return WRITE_ACK;
        default: return null;
      }
    }
    
    public static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static com.google.protobuf.Internal.EnumLiteMap<CommandType>
        internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<CommandType>() {
            public CommandType findValueByNumber(int number) {
              return CommandType.valueOf(number);
            }
          };
    
    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      return getDescriptor().getValues().get(index);
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return org.eligosource.eventsourced.core.JournalProtocol.getDescriptor().getEnumTypes().get(0);
    }
    
    private static final CommandType[] VALUES = {
      WRITE_IN, WRITE_OUT, WRITE_ACK, 
    };
    
    public static CommandType valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      return VALUES[desc.getIndex()];
    }
    
    private final int index;
    private final int value;
    
    private CommandType(int index, int value) {
      this.index = index;
      this.value = value;
    }
    
    // @@protoc_insertion_point(enum_scope:CommandType)
  }
  
  public interface CommandProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // required .CommandType commandType = 1;
    boolean hasCommandType();
    org.eligosource.eventsourced.core.JournalProtocol.CommandType getCommandType();
    
    // optional .MessageProtocol message = 2;
    boolean hasMessage();
    org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol getMessage();
    org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder getMessageOrBuilder();
    
    // optional int32 processorId = 3;
    boolean hasProcessorId();
    int getProcessorId();
    
    // optional int32 channelId = 4;
    boolean hasChannelId();
    int getChannelId();
    
    // optional int64 sequenceNr = 5;
    boolean hasSequenceNr();
    long getSequenceNr();
  }
  public static final class CommandProtocol extends
      com.google.protobuf.GeneratedMessage
      implements CommandProtocolOrBuilder {
    // Use CommandProtocol.newBuilder() to construct.
    private CommandProtocol(Builder builder) {
      super(builder);
    }
    private CommandProtocol(boolean noInit) {}
    
    private static final CommandProtocol defaultInstance;
    public static CommandProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public CommandProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eligosource.eventsourced.core.JournalProtocol.internal_static_CommandProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eligosource.eventsourced.core.JournalProtocol.internal_static_CommandProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // required .CommandType commandType = 1;
    public static final int COMMANDTYPE_FIELD_NUMBER = 1;
    private org.eligosource.eventsourced.core.JournalProtocol.CommandType commandType_;
    public boolean hasCommandType() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public org.eligosource.eventsourced.core.JournalProtocol.CommandType getCommandType() {
      return commandType_;
    }
    
    // optional .MessageProtocol message = 2;
    public static final int MESSAGE_FIELD_NUMBER = 2;
    private org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol message_;
    public boolean hasMessage() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol getMessage() {
      return message_;
    }
    public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder getMessageOrBuilder() {
      return message_;
    }
    
    // optional int32 processorId = 3;
    public static final int PROCESSORID_FIELD_NUMBER = 3;
    private int processorId_;
    public boolean hasProcessorId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getProcessorId() {
      return processorId_;
    }
    
    // optional int32 channelId = 4;
    public static final int CHANNELID_FIELD_NUMBER = 4;
    private int channelId_;
    public boolean hasChannelId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getChannelId() {
      return channelId_;
    }
    
    // optional int64 sequenceNr = 5;
    public static final int SEQUENCENR_FIELD_NUMBER = 5;
    private long sequenceNr_;
    public boolean hasSequenceNr() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getSequenceNr() {
      return sequenceNr_;
    }
    
    private void initFields() {
      commandType_ = org.eligosource.eventsourced.core.JournalProtocol.CommandType.WRITE_IN;
      message_ = org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance();
      processorId_ = 0;
      channelId_ = 0;
      sequenceNr_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      if (!hasCommandType()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeEnum(1, commandType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeMessage(2, message_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(3, processorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(4, channelId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(5, sequenceNr_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, commandType_.getNumber());
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, message_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, processorId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, channelId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(5, sequenceNr_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.eligosource.eventsourced.core.JournalProtocol.CommandProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eligosource.eventsourced.core.JournalProtocol.internal_static_CommandProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eligosource.eventsourced.core.JournalProtocol.internal_static_CommandProtocol_fieldAccessorTable;
      }
      
      // Construct using org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
          getMessageFieldBuilder();
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        commandType_ = org.eligosource.eventsourced.core.JournalProtocol.CommandType.WRITE_IN;
        bitField0_ = (bitField0_ & ~0x00000001);
        if (messageBuilder_ == null) {
          message_ = org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        processorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        channelId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sequenceNr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.getDescriptor();
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol getDefaultInstanceForType() {
        return org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.getDefaultInstance();
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol build() {
        org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol buildPartial() {
        org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol result = new org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.commandType_ = commandType_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        if (messageBuilder_ == null) {
          result.message_ = message_;
        } else {
          result.message_ = messageBuilder_.build();
        }
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.processorId_ = processorId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.channelId_ = channelId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sequenceNr_ = sequenceNr_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol) {
          return mergeFrom((org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol other) {
        if (other == org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.getDefaultInstance()) return this;
        if (other.hasCommandType()) {
          setCommandType(other.getCommandType());
        }
        if (other.hasMessage()) {
          mergeMessage(other.getMessage());
        }
        if (other.hasProcessorId()) {
          setProcessorId(other.getProcessorId());
        }
        if (other.hasChannelId()) {
          setChannelId(other.getChannelId());
        }
        if (other.hasSequenceNr()) {
          setSequenceNr(other.getSequenceNr());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        if (!hasCommandType()) {
          
          return false;
        }
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 8: {
              int rawValue = input.readEnum();
              org.eligosource.eventsourced.core.JournalProtocol.CommandType value = org.eligosource.eventsourced.core.JournalProtocol.CommandType.valueOf(rawValue);
              if (value == null) {
                unknownFields.mergeVarintField(1, rawValue);
              } else {
                bitField0_ |= 0x00000001;
                commandType_ = value;
              }
              break;
            }
            case 18: {
              org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder subBuilder = org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.newBuilder();
              if (hasMessage()) {
                subBuilder.mergeFrom(getMessage());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMessage(subBuilder.buildPartial());
              break;
            }
            case 24: {
              bitField0_ |= 0x00000004;
              processorId_ = input.readInt32();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000008;
              channelId_ = input.readInt32();
              break;
            }
            case 40: {
              bitField0_ |= 0x00000010;
              sequenceNr_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // required .CommandType commandType = 1;
      private org.eligosource.eventsourced.core.JournalProtocol.CommandType commandType_ = org.eligosource.eventsourced.core.JournalProtocol.CommandType.WRITE_IN;
      public boolean hasCommandType() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public org.eligosource.eventsourced.core.JournalProtocol.CommandType getCommandType() {
        return commandType_;
      }
      public Builder setCommandType(org.eligosource.eventsourced.core.JournalProtocol.CommandType value) {
        if (value == null) {
          throw new NullPointerException();
        }
        bitField0_ |= 0x00000001;
        commandType_ = value;
        onChanged();
        return this;
      }
      public Builder clearCommandType() {
        bitField0_ = (bitField0_ & ~0x00000001);
        commandType_ = org.eligosource.eventsourced.core.JournalProtocol.CommandType.WRITE_IN;
        onChanged();
        return this;
      }
      
      // optional .MessageProtocol message = 2;
      private org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol message_ = org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance();
      private com.google.protobuf.SingleFieldBuilder<
          org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder> messageBuilder_;
      public boolean hasMessage() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol getMessage() {
        if (messageBuilder_ == null) {
          return message_;
        } else {
          return messageBuilder_.getMessage();
        }
      }
      public Builder setMessage(org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol value) {
        if (messageBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          message_ = value;
          onChanged();
        } else {
          messageBuilder_.setMessage(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder setMessage(
          org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder builderForValue) {
        if (messageBuilder_ == null) {
          message_ = builderForValue.build();
          onChanged();
        } else {
          messageBuilder_.setMessage(builderForValue.build());
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder mergeMessage(org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol value) {
        if (messageBuilder_ == null) {
          if (((bitField0_ & 0x00000002) == 0x00000002) &&
              message_ != org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance()) {
            message_ =
              org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.newBuilder(message_).mergeFrom(value).buildPartial();
          } else {
            message_ = value;
          }
          onChanged();
        } else {
          messageBuilder_.mergeFrom(value);
        }
        bitField0_ |= 0x00000002;
        return this;
      }
      public Builder clearMessage() {
        if (messageBuilder_ == null) {
          message_ = org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance();
          onChanged();
        } else {
          messageBuilder_.clear();
        }
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder getMessageBuilder() {
        bitField0_ |= 0x00000002;
        onChanged();
        return getMessageFieldBuilder().getBuilder();
      }
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder getMessageOrBuilder() {
        if (messageBuilder_ != null) {
          return messageBuilder_.getMessageOrBuilder();
        } else {
          return message_;
        }
      }
      private com.google.protobuf.SingleFieldBuilder<
          org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder> 
          getMessageFieldBuilder() {
        if (messageBuilder_ == null) {
          messageBuilder_ = new com.google.protobuf.SingleFieldBuilder<
              org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder, org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder>(
                  message_,
                  getParentForChildren(),
                  isClean());
          message_ = null;
        }
        return messageBuilder_;
      }
      
      // optional int32 processorId = 3;
      private int processorId_ ;
      public boolean hasProcessorId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getProcessorId() {
        return processorId_;
      }
      public Builder setProcessorId(int value) {
        bitField0_ |= 0x00000004;
        processorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcessorId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        processorId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 channelId = 4;
      private int channelId_ ;
      public boolean hasChannelId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getChannelId() {
        return channelId_;
      }
      public Builder setChannelId(int value) {
        bitField0_ |= 0x00000008;
        channelId_ = value;
        onChanged();
        return this;
      }
      public Builder clearChannelId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        channelId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 sequenceNr = 5;
      private long sequenceNr_ ;
      public boolean hasSequenceNr() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getSequenceNr() {
        return sequenceNr_;
      }
      public Builder setSequenceNr(long value) {
        bitField0_ |= 0x00000010;
        sequenceNr_ = value;
        onChanged();
        return this;
      }
      public Builder clearSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sequenceNr_ = 0L;
        onChanged();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:CommandProtocol)
    }
    
    static {
      defaultInstance = new CommandProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:CommandProtocol)
  }
  
  public interface MessageProtocolOrBuilder
      extends com.google.protobuf.MessageOrBuilder {
    
    // optional bytes event = 2;
    boolean hasEvent();
    com.google.protobuf.ByteString getEvent();
    
    // optional bytes eventManifest = 3;
    boolean hasEventManifest();
    com.google.protobuf.ByteString getEventManifest();
    
    // optional int32 eventSerializerId = 4;
    boolean hasEventSerializerId();
    int getEventSerializerId();
    
    // optional int32 processorId = 6;
    boolean hasProcessorId();
    int getProcessorId();
    
    // optional int64 sequenceNr = 7;
    boolean hasSequenceNr();
    long getSequenceNr();
    
    // optional int64 timestamp = 9;
    boolean hasTimestamp();
    long getTimestamp();
    
    // optional string senderPath = 8;
    boolean hasSenderPath();
    String getSenderPath();
  }
  public static final class MessageProtocol extends
      com.google.protobuf.GeneratedMessage
      implements MessageProtocolOrBuilder {
    // Use MessageProtocol.newBuilder() to construct.
    private MessageProtocol(Builder builder) {
      super(builder);
    }
    private MessageProtocol(boolean noInit) {}
    
    private static final MessageProtocol defaultInstance;
    public static MessageProtocol getDefaultInstance() {
      return defaultInstance;
    }
    
    public MessageProtocol getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return org.eligosource.eventsourced.core.JournalProtocol.internal_static_MessageProtocol_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return org.eligosource.eventsourced.core.JournalProtocol.internal_static_MessageProtocol_fieldAccessorTable;
    }
    
    private int bitField0_;
    // optional bytes event = 2;
    public static final int EVENT_FIELD_NUMBER = 2;
    private com.google.protobuf.ByteString event_;
    public boolean hasEvent() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    public com.google.protobuf.ByteString getEvent() {
      return event_;
    }
    
    // optional bytes eventManifest = 3;
    public static final int EVENTMANIFEST_FIELD_NUMBER = 3;
    private com.google.protobuf.ByteString eventManifest_;
    public boolean hasEventManifest() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    public com.google.protobuf.ByteString getEventManifest() {
      return eventManifest_;
    }
    
    // optional int32 eventSerializerId = 4;
    public static final int EVENTSERIALIZERID_FIELD_NUMBER = 4;
    private int eventSerializerId_;
    public boolean hasEventSerializerId() {
      return ((bitField0_ & 0x00000004) == 0x00000004);
    }
    public int getEventSerializerId() {
      return eventSerializerId_;
    }
    
    // optional int32 processorId = 6;
    public static final int PROCESSORID_FIELD_NUMBER = 6;
    private int processorId_;
    public boolean hasProcessorId() {
      return ((bitField0_ & 0x00000008) == 0x00000008);
    }
    public int getProcessorId() {
      return processorId_;
    }
    
    // optional int64 sequenceNr = 7;
    public static final int SEQUENCENR_FIELD_NUMBER = 7;
    private long sequenceNr_;
    public boolean hasSequenceNr() {
      return ((bitField0_ & 0x00000010) == 0x00000010);
    }
    public long getSequenceNr() {
      return sequenceNr_;
    }
    
    // optional int64 timestamp = 9;
    public static final int TIMESTAMP_FIELD_NUMBER = 9;
    private long timestamp_;
    public boolean hasTimestamp() {
      return ((bitField0_ & 0x00000020) == 0x00000020);
    }
    public long getTimestamp() {
      return timestamp_;
    }
    
    // optional string senderPath = 8;
    public static final int SENDERPATH_FIELD_NUMBER = 8;
    private java.lang.Object senderPath_;
    public boolean hasSenderPath() {
      return ((bitField0_ & 0x00000040) == 0x00000040);
    }
    public String getSenderPath() {
      java.lang.Object ref = senderPath_;
      if (ref instanceof String) {
        return (String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        String s = bs.toStringUtf8();
        if (com.google.protobuf.Internal.isValidUtf8(bs)) {
          senderPath_ = s;
        }
        return s;
      }
    }
    private com.google.protobuf.ByteString getSenderPathBytes() {
      java.lang.Object ref = senderPath_;
      if (ref instanceof String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8((String) ref);
        senderPath_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }
    
    private void initFields() {
      event_ = com.google.protobuf.ByteString.EMPTY;
      eventManifest_ = com.google.protobuf.ByteString.EMPTY;
      eventSerializerId_ = 0;
      processorId_ = 0;
      sequenceNr_ = 0L;
      timestamp_ = 0L;
      senderPath_ = "";
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized != -1) return isInitialized == 1;
      
      memoizedIsInitialized = 1;
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeBytes(2, event_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeBytes(3, eventManifest_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        output.writeInt32(4, eventSerializerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        output.writeInt32(6, processorId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        output.writeInt64(7, sequenceNr_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        output.writeBytes(8, getSenderPathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        output.writeInt64(9, timestamp_);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(2, event_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(3, eventManifest_);
      }
      if (((bitField0_ & 0x00000004) == 0x00000004)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, eventSerializerId_);
      }
      if (((bitField0_ & 0x00000008) == 0x00000008)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(6, processorId_);
      }
      if (((bitField0_ & 0x00000010) == 0x00000010)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(7, sequenceNr_);
      }
      if (((bitField0_ & 0x00000040) == 0x00000040)) {
        size += com.google.protobuf.CodedOutputStream
          .computeBytesSize(8, getSenderPathBytes());
      }
      if (((bitField0_ & 0x00000020) == 0x00000020)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(9, timestamp_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }
    
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder>
       implements org.eligosource.eventsourced.core.JournalProtocol.MessageProtocolOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return org.eligosource.eventsourced.core.JournalProtocol.internal_static_MessageProtocol_descriptor;
      }
      
      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return org.eligosource.eventsourced.core.JournalProtocol.internal_static_MessageProtocol_fieldAccessorTable;
      }
      
      // Construct using org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }
      
      private Builder(com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }
      
      public Builder clear() {
        super.clear();
        event_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000001);
        eventManifest_ = com.google.protobuf.ByteString.EMPTY;
        bitField0_ = (bitField0_ & ~0x00000002);
        eventSerializerId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000004);
        processorId_ = 0;
        bitField0_ = (bitField0_ & ~0x00000008);
        sequenceNr_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000010);
        timestamp_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000020);
        senderPath_ = "";
        bitField0_ = (bitField0_ & ~0x00000040);
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDescriptor();
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol getDefaultInstanceForType() {
        return org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance();
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol build() {
        org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }
      
      private org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return result;
      }
      
      public org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol buildPartial() {
        org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol result = new org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.event_ = event_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.eventManifest_ = eventManifest_;
        if (((from_bitField0_ & 0x00000004) == 0x00000004)) {
          to_bitField0_ |= 0x00000004;
        }
        result.eventSerializerId_ = eventSerializerId_;
        if (((from_bitField0_ & 0x00000008) == 0x00000008)) {
          to_bitField0_ |= 0x00000008;
        }
        result.processorId_ = processorId_;
        if (((from_bitField0_ & 0x00000010) == 0x00000010)) {
          to_bitField0_ |= 0x00000010;
        }
        result.sequenceNr_ = sequenceNr_;
        if (((from_bitField0_ & 0x00000020) == 0x00000020)) {
          to_bitField0_ |= 0x00000020;
        }
        result.timestamp_ = timestamp_;
        if (((from_bitField0_ & 0x00000040) == 0x00000040)) {
          to_bitField0_ |= 0x00000040;
        }
        result.senderPath_ = senderPath_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol) {
          return mergeFrom((org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol other) {
        if (other == org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.getDefaultInstance()) return this;
        if (other.hasEvent()) {
          setEvent(other.getEvent());
        }
        if (other.hasEventManifest()) {
          setEventManifest(other.getEventManifest());
        }
        if (other.hasEventSerializerId()) {
          setEventSerializerId(other.getEventSerializerId());
        }
        if (other.hasProcessorId()) {
          setProcessorId(other.getProcessorId());
        }
        if (other.hasSequenceNr()) {
          setSequenceNr(other.getSequenceNr());
        }
        if (other.hasTimestamp()) {
          setTimestamp(other.getTimestamp());
        }
        if (other.hasSenderPath()) {
          setSenderPath(other.getSenderPath());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public final boolean isInitialized() {
        return true;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              onChanged();
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                onChanged();
                return this;
              }
              break;
            }
            case 18: {
              bitField0_ |= 0x00000001;
              event_ = input.readBytes();
              break;
            }
            case 26: {
              bitField0_ |= 0x00000002;
              eventManifest_ = input.readBytes();
              break;
            }
            case 32: {
              bitField0_ |= 0x00000004;
              eventSerializerId_ = input.readInt32();
              break;
            }
            case 48: {
              bitField0_ |= 0x00000008;
              processorId_ = input.readInt32();
              break;
            }
            case 56: {
              bitField0_ |= 0x00000010;
              sequenceNr_ = input.readInt64();
              break;
            }
            case 66: {
              bitField0_ |= 0x00000040;
              senderPath_ = input.readBytes();
              break;
            }
            case 72: {
              bitField0_ |= 0x00000020;
              timestamp_ = input.readInt64();
              break;
            }
          }
        }
      }
      
      private int bitField0_;
      
      // optional bytes event = 2;
      private com.google.protobuf.ByteString event_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasEvent() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      public com.google.protobuf.ByteString getEvent() {
        return event_;
      }
      public Builder setEvent(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000001;
        event_ = value;
        onChanged();
        return this;
      }
      public Builder clearEvent() {
        bitField0_ = (bitField0_ & ~0x00000001);
        event_ = getDefaultInstance().getEvent();
        onChanged();
        return this;
      }
      
      // optional bytes eventManifest = 3;
      private com.google.protobuf.ByteString eventManifest_ = com.google.protobuf.ByteString.EMPTY;
      public boolean hasEventManifest() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      public com.google.protobuf.ByteString getEventManifest() {
        return eventManifest_;
      }
      public Builder setEventManifest(com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000002;
        eventManifest_ = value;
        onChanged();
        return this;
      }
      public Builder clearEventManifest() {
        bitField0_ = (bitField0_ & ~0x00000002);
        eventManifest_ = getDefaultInstance().getEventManifest();
        onChanged();
        return this;
      }
      
      // optional int32 eventSerializerId = 4;
      private int eventSerializerId_ ;
      public boolean hasEventSerializerId() {
        return ((bitField0_ & 0x00000004) == 0x00000004);
      }
      public int getEventSerializerId() {
        return eventSerializerId_;
      }
      public Builder setEventSerializerId(int value) {
        bitField0_ |= 0x00000004;
        eventSerializerId_ = value;
        onChanged();
        return this;
      }
      public Builder clearEventSerializerId() {
        bitField0_ = (bitField0_ & ~0x00000004);
        eventSerializerId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int32 processorId = 6;
      private int processorId_ ;
      public boolean hasProcessorId() {
        return ((bitField0_ & 0x00000008) == 0x00000008);
      }
      public int getProcessorId() {
        return processorId_;
      }
      public Builder setProcessorId(int value) {
        bitField0_ |= 0x00000008;
        processorId_ = value;
        onChanged();
        return this;
      }
      public Builder clearProcessorId() {
        bitField0_ = (bitField0_ & ~0x00000008);
        processorId_ = 0;
        onChanged();
        return this;
      }
      
      // optional int64 sequenceNr = 7;
      private long sequenceNr_ ;
      public boolean hasSequenceNr() {
        return ((bitField0_ & 0x00000010) == 0x00000010);
      }
      public long getSequenceNr() {
        return sequenceNr_;
      }
      public Builder setSequenceNr(long value) {
        bitField0_ |= 0x00000010;
        sequenceNr_ = value;
        onChanged();
        return this;
      }
      public Builder clearSequenceNr() {
        bitField0_ = (bitField0_ & ~0x00000010);
        sequenceNr_ = 0L;
        onChanged();
        return this;
      }
      
      // optional int64 timestamp = 9;
      private long timestamp_ ;
      public boolean hasTimestamp() {
        return ((bitField0_ & 0x00000020) == 0x00000020);
      }
      public long getTimestamp() {
        return timestamp_;
      }
      public Builder setTimestamp(long value) {
        bitField0_ |= 0x00000020;
        timestamp_ = value;
        onChanged();
        return this;
      }
      public Builder clearTimestamp() {
        bitField0_ = (bitField0_ & ~0x00000020);
        timestamp_ = 0L;
        onChanged();
        return this;
      }
      
      // optional string senderPath = 8;
      private java.lang.Object senderPath_ = "";
      public boolean hasSenderPath() {
        return ((bitField0_ & 0x00000040) == 0x00000040);
      }
      public String getSenderPath() {
        java.lang.Object ref = senderPath_;
        if (!(ref instanceof String)) {
          String s = ((com.google.protobuf.ByteString) ref).toStringUtf8();
          senderPath_ = s;
          return s;
        } else {
          return (String) ref;
        }
      }
      public Builder setSenderPath(String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  bitField0_ |= 0x00000040;
        senderPath_ = value;
        onChanged();
        return this;
      }
      public Builder clearSenderPath() {
        bitField0_ = (bitField0_ & ~0x00000040);
        senderPath_ = getDefaultInstance().getSenderPath();
        onChanged();
        return this;
      }
      void setSenderPath(com.google.protobuf.ByteString value) {
        bitField0_ |= 0x00000040;
        senderPath_ = value;
        onChanged();
      }
      
      // @@protoc_insertion_point(builder_scope:MessageProtocol)
    }
    
    static {
      defaultInstance = new MessageProtocol(true);
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:MessageProtocol)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_CommandProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_CommandProtocol_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_MessageProtocol_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_MessageProtocol_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\025JournalProtocol.proto\"\223\001\n\017CommandProto" +
      "col\022!\n\013commandType\030\001 \002(\0162\014.CommandType\022!" +
      "\n\007message\030\002 \001(\0132\020.MessageProtocol\022\023\n\013pro" +
      "cessorId\030\003 \001(\005\022\021\n\tchannelId\030\004 \001(\005\022\022\n\nseq" +
      "uenceNr\030\005 \001(\003\"\242\001\n\017MessageProtocol\022\r\n\005eve" +
      "nt\030\002 \001(\014\022\025\n\reventManifest\030\003 \001(\014\022\031\n\021event" +
      "SerializerId\030\004 \001(\005\022\023\n\013processorId\030\006 \001(\005\022" +
      "\022\n\nsequenceNr\030\007 \001(\003\022\021\n\ttimestamp\030\t \001(\003\022\022" +
      "\n\nsenderPath\030\010 \001(\t*9\n\013CommandType\022\014\n\010WRI" +
      "TE_IN\020\001\022\r\n\tWRITE_OUT\020\002\022\r\n\tWRITE_ACK\020\003B4\n",
      "!org.eligosource.eventsourced.coreB\017Jour" +
      "nalProtocol"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_CommandProtocol_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_CommandProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_CommandProtocol_descriptor,
              new java.lang.String[] { "CommandType", "Message", "ProcessorId", "ChannelId", "SequenceNr", },
              org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.class,
              org.eligosource.eventsourced.core.JournalProtocol.CommandProtocol.Builder.class);
          internal_static_MessageProtocol_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_MessageProtocol_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_MessageProtocol_descriptor,
              new java.lang.String[] { "Event", "EventManifest", "EventSerializerId", "ProcessorId", "SequenceNr", "Timestamp", "SenderPath", },
              org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.class,
              org.eligosource.eventsourced.core.JournalProtocol.MessageProtocol.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
  }
  
  // @@protoc_insertion_point(outer_class_scope)
}
